/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas.login;

import Servicios.login.ServicioUsuario;
import Servicios.login.ServicioUsuarioImpl;
import controlador.login.LoginControlador;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.login.Login;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author fede_
 */
public class Registro extends javax.swing.JFrame {

    private final ServicioUsuario servicioUsuario;

    public Registro() {
        initComponents();
        servicioUsuario = new ServicioUsuarioImpl();
        this.setLocationRelativeTo(null); //SIRVE PARA QUE APARESCA EN EL CENTRO LA VENTANA
        this.setTitle("Registro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblNombreDeUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btncasilla = new javax.swing.JCheckBox();
        btnVolverRegistro = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtNombreDeUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 102, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("NOMBRE");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 20));

        lblApellido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(204, 204, 204));
        lblApellido.setText("APELLIDO");
        jPanel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

        lblNombreDeUsuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombreDeUsuario.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreDeUsuario.setText("NOMBRE DE USUARIO");
        jPanel1.add(lblNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        lblContraseña.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblContraseña.setForeground(new java.awt.Color(204, 204, 204));
        lblContraseña.setText("CONTRASEÑA");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 20));

        btnRegistro.setBackground(new java.awt.Color(0, 153, 204));
        btnRegistro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnRegistro.setText("REGISTRAR");
        btnRegistro.setBorder(null);
        btnRegistro.setBorderPainted(false);
        btnRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistroMouseClicked(evt);
            }
        });
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 110, 40));

        txtApellido.setBackground(new java.awt.Color(0, 51, 102));
        txtApellido.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setBorder(null);
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMouseClicked(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 230, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 230, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 230, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 230, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 230, 10));

        btncasilla.setBackground(new java.awt.Color(0, 51, 102));
        btncasilla.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btncasilla.setForeground(new java.awt.Color(204, 204, 204));
        btncasilla.setText("Acepta los terminos y condiciones de uso");
        btncasilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncasillaActionPerformed(evt);
            }
        });
        jPanel1.add(btncasilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 250, -1));

        btnVolverRegistro.setBackground(new java.awt.Color(0, 153, 204));
        btnVolverRegistro.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnVolverRegistro.setText("VOLVER");
        btnVolverRegistro.setBorder(null);
        btnVolverRegistro.setBorderPainted(false);
        btnVolverRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 110, 40));

        txtNombre.setBackground(new java.awt.Color(0, 51, 102));
        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setBorder(null);
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 230, 20));

        txtNombreDeUsuario.setBackground(new java.awt.Color(0, 51, 102));
        txtNombreDeUsuario.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreDeUsuario.setBorder(null);
        txtNombreDeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreDeUsuarioMouseClicked(evt);
            }
        });
        jPanel1.add(txtNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 184, 230, 20));

        txtContraseña.setBackground(new java.awt.Color(0, 51, 102));
        txtContraseña.setForeground(new java.awt.Color(102, 102, 102));
        txtContraseña.setBorder(null);
        txtContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtContraseñaMouseClicked(evt);
            }
        });
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 244, 230, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 340, 390));

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("REGISTRO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 150)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic_person_add_128_28581.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 130, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        /* IniciarSesion a = new IniciarSesion();   //COMENTADO POR QUE SOLO DEBERIA REGISTRAR NO VOLVER AL INICIO
         a.setVisible(true);
         this.setVisible(false);*/
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btncasillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncasillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncasillaActionPerformed

    private void txtApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMouseClicked
        // TODO add your handling code here:
        txtApellido.setText(""); //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtApellidoMouseClicked

    private void btnVolverRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverRegistroActionPerformed
        // TODO add your handling code here:
        IniciarSesion V = new IniciarSesion();
        V.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverRegistroActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        txtNombre.setText("");
        //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreDeUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreDeUsuarioMouseClicked

        txtNombreDeUsuario.setText(""); //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtNombreDeUsuarioMouseClicked

    private void txtContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContraseñaMouseClicked
        // TODO add your handling code here:
        txtContraseña.setText(""); //SIRVE PARA PODER ESCRIBIR SINO NO TE DEJA LA BARRA
    }//GEN-LAST:event_txtContraseñaMouseClicked

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMouseClicked
      if(txtNombre.getText().equals("") ||txtApellido.getText().equals("")||txtContraseña.getText().equals("")||txtNombreDeUsuario.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Campos Vacios, Llenelos para seguir ","ERROR",JOptionPane.ERROR_MESSAGE);
       }else{
        
        if (btncasilla.isSelected() == true) {
            JOptionPane.showMessageDialog(this, "Usted se a registrado correctamente", "Registro", JOptionPane.INFORMATION_MESSAGE);
            String nombre = txtNombre.getText().trim();
            String contraseña = BCrypt.hashpw(txtContraseña.getPassword().toString(), BCrypt.gensalt(12));
            String nombreDeUsuario = txtNombreDeUsuario.getText().trim();
            String apellido = txtApellido.getText().trim();

            Login item = new Login(nombre, apellido, nombreDeUsuario, contraseña);

            try {
                int addUsuarios = LoginControlador.addUsuarios(item);

                if (addUsuarios > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Registro exitoso!");
                }
            } catch (ClassNotFoundException | SQLException e) {
                e.printStackTrace();
            } finally {

            }
            IniciarSesion V = new IniciarSesion();

            V.setVisible(true);
            dispose();
            servicioUsuario.save(item);
            item.setNombre(this.txtNombre.getText());
            item.setApellido(this.txtApellido.getText());
            item.setContraseña(this.txtContraseña.getText());
            item.setNombreDeUsuario(this.txtNombreDeUsuario.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Casilla no marcada", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
      }
        /*
         JOptionPane.showMessageDialog(this, "Usted se a registrado correctamente", "Registro", JOptionPane.INFORMATION_MESSAGE);
         Login item = new Login();

         item.setNombre(this.txtNombre.getText());
         item.setApellido(this.txtApellido.getText());
         item.setContraseña(this.txtContraseña.getText());
         item.setNombreDeUsuario(this.txtNombreDeUsuario.getText());

         servicioUsuario.save(item);
         IniciarSesion V = new IniciarSesion();
         V.setVisible(true);
         dispose();
         */
    }//GEN-LAST:event_btnRegistroMouseClicked

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }


    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnVolverRegistro;
    private javax.swing.JCheckBox btncasilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreDeUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreDeUsuario;
    // End of variables declaration//GEN-END:variables
}
